Ext.define('Eway.store.Minute', {
	extend: 'Ext.data.Store',
	
	model: 'Eway.model.Dict',
	
	data: [{value:'00', display:'00'}, 
	       {value:'01', display:'01'}, 
	       {value:'02', display:'02'}, 
	       {value:'03', display:'03'}, 
	       {value:'04', display:'04'}, 
	       {value:'05', display:'05'}, 
	       {value:'06', display:'06'}, 
	       {value:'07', display:'07'}, 
	       {value:'08', display:'08'}, 
	       {value:'09', display:'09'}, 
	       {value:'10', display:'10'}, 
	       {value:'11', display:'11'}, 
	       {value:'12', display:'12'}, 
	       {value:'13', display:'13'}, 
	       {value:'14', display:'14'}, 
	       {value:'15', display:'15'}, 
	       {value:'16', display:'16'}, 
	       {value:'17', display:'17'}, 
	       {value:'18', display:'18'}, 
	       {value:'19', display:'19'}, 
	       {value:'20', display:'20'}, 
	       {value:'21', display:'21'}, 
	       {value:'22', display:'22'}, 
	       {value:'23', display:'23'}, 
	       {value:'24', display:'24'}, 
	       {value:'25', display:'25'}, 
	       {value:'26', display:'26'}, 
	       {value:'27', display:'27'}, 
	       {value:'28', display:'28'}, 
	       {value:'29', display:'29'}, 
	       {value:'30', display:'30'}, 
	       {value:'31', display:'31'}, 
	       {value:'32', display:'32'}, 
	       {value:'33', display:'33'}, 
	       {value:'34', display:'34'}, 
	       {value:'35', display:'35'}, 
	       {value:'36', display:'36'}, 
	       {value:'37', display:'37'}, 
	       {value:'38', display:'38'}, 
	       {value:'39', display:'39'}, 
	       {value:'40', display:'40'}, 
	       {value:'41', display:'41'}, 
	       {value:'42', display:'42'}, 
	       {value:'43', display:'43'}, 
	       {value:'44', display:'44'}, 
	       {value:'45', display:'45'}, 
	       {value:'46', display:'46'}, 
	       {value:'47', display:'47'}, 
	       {value:'48', display:'48'}, 
	       {value:'49', display:'49'}, 
	       {value:'50', display:'50'}, 
	       {value:'51', display:'51'}, 
	       {value:'52', display:'52'}, 
	       {value:'53', display:'53'}, 
	       {value:'54', display:'54'}, 
	       {value:'55', display:'55'}, 
	       {value:'56', display:'56'}, 
	       {value:'57', display:'57'}, 
	       {value:'58', display:'58'}, 
	       {value:'59', display:'59'}
	       
	      ]
});
