INSERT INTO DEV_CATALOG(ID,NAME,CATALOG_NO) VALUES('1', 'ATM', '01');
INSERT INTO DEV_CATALOG(ID,NAME,CATALOG_NO) VALUES('2', 'CRS', '02');
INSERT INTO DEV_CATALOG(ID,NAME,CATALOG_NO) VALUES('3', 'BSM', '03');

INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('1', 'IDC', '0001', 'Card reader','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('2', 'JPR', '0002', 'Deposit module','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('3', 'RPR', '0003', 'Voucher printer','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('4', 'CDM', '0004', 'Draw module','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('5', 'CIM', '0005', 'Deposit module','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('6', 'PIN', '0006', 'Pin keyboard','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('7', 'TTU', '0007', 'Text terminal','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('8', 'SIU', '0008', 'Sensor','1');

INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('9', 'ISC', '0009', 'I.D.card scanner','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('10', 'ICC', '0010', 'Issue card module','1');
INSERT INTO DEV_MODULE(ID,NAME,MOD_NO,NOTE,IS_CASE) VALUES ('11', 'FGP', '0011', 'FingerPrints','1');

INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('1', '0', 'Monitor service file-saving path', 'fish_home', 'd:\\fish_home');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('2', '1', 'Remote service listen port', 'atm_port', '80');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('3', '1', 'ATM APP save rule', 'atm_log_file_cfg', 'bizLog_{terminalId}_{YYYY-MM-DD}.zip');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('4', '1', 'ATM APP save path', 'atm_log_doc', 'c:\\yihua\\gump\\log');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('5', '1', 'Get device offline(unit:minute)', 'device_offline', '30');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('8', '0', 'Sys register_serial', 'register_serial', 'V10520-FEDDJD-A76104-PJFDGK-HEDFEF1150');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('9', '1', 'ATM time synchronization switch(ON/OFF)', 'check_time', 'ON');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('0',  null, 'root','Menu',null,'0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A',  null, 'info','System','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A01',  null, 'bankOrg','Organization','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0101',  null, 'bankOrgQuery','Search','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0102',  null, 'bankOrgAdd','Add','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0103',  null, 'bankOrgUpdate','Update','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0104',  null, 'bankOrgDel','Remove','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0105',  null, 'bankOrgAdmin','Manager','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0106',  null, 'bankOrgMove','Move','A01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A02',  null, 'bankPer','BankPerson','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0201',  null, 'bankPerQuery','Query','A02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0202',  null, 'bankPerAdd','Add','A02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0203',  null, 'bankPerUpdate','Modify','A02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0204',  null, 'bankPerDel','Remove','A02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0205',  null, 'bankPerlink','LinkDevice','A02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A03',  null, 'serviceOrg','ServiceOrg','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0301',  null, 'serviceOrgQuery','Query','A03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0302',  null, 'serviceOrgAdd','Add','A03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0303',  null, 'serviceOrgUpdate','Modify','A03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0304',  null, 'serviceOrgDel','Remove','A03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0305',  null, 'serviceOrgAdmin','Manager','A03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A04',  null, 'servicePer','ServicePer','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0401',  null, 'servicePerQuery','Query','A04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0402',  null, 'servicePerAdd','Add','A04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0403',  null, 'servicePerUpdate','Modify','A04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0404',  null, 'servicePerDel','Remove','A04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0405',  null, 'servicePerlink','Link device','A04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A05',  null, 'user','User','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0501',  null, 'userQuery','Query','A05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0502',  null, 'userAdd','Add','A05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0503',  null, 'userUpdate','Modify','A05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0504',  null, 'userDel','Remove','A05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A07',  null,'userLog','UserLog','A','0');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A08', null, 'role','Role','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0801',  null, 'roleQuery','Query','A08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0802',  null, 'roleAdd','Add','A08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0803',  null, 'roleUpdate','Modify','A08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0804',  null, 'roleDel','Remove','A08','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A09', null, 'configuration','SysSetting','A','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0901',  null, 'configurationUpdateQuery','Query','A09','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A0902',  null, 'configurationUpdate','Modify','A09','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('A10',  null, 'serviceThread','SysMaintenance','A','0');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B',  null, 'deviceMgr','Device','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B01', null, 'device','DevInfo','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0101',  null, 'deviceQuery','Query','B01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0102',  null, 'deviceAdd','Add','B01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0103',  null, 'deviceUpdate','Modify','B01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0104',  null, 'deviceDel','Remove','B01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B02', null, 'atmCatalog','AtmCatalog','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0201', null, 'atmCatalogQuery','Query','B02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B03', null, 'atmBrand','DevBrand','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0301',  null, 'atmBrandQuery','Query','B03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0302',  null, 'atmBrandAdd','Add','B03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0303',  null, 'atmBrandUpdate','Modify','B03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0304',  null, 'atmBrandDel','Remove','B03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B04', null, 'atmType','DevType','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0401',  null, 'atmTypeQuery','Query','B04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0402',  null, 'atmTypeAdd','Add','B04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0403',  null, 'atmTypeUpdate','Modify','B04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0404',  null, 'atmTypeDel','Remove','B04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B05', null, 'atmGroup','DevGroup','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0501',  null, 'atmGroupQuery','Query','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0502',  null, 'atmGroupAdd','Add','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0503',  null, 'atmGroupUpdate','Modify','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0504',  null, 'atmGroupDel','Remove','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0505',  null, 'atmGroupDeviceQuery','QueryDevice','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0506',  null, 'atmGroupDeviceAdd','Add','B05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0507',  null, 'atmGroupDeviceDel','Remove','B05','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B06', null, 'device_quittingNotice','Stop','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0601', null, 'quittingNoticeQuery','Query','B06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0602', null, 'quittingNoticeAdd','Add','B06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0603', null, 'quittingNoticeUpdate','Modify','B06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0604', null, 'quittingNoticeDel','Remove','B06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B07', null, 'device_move','DevMove','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0701', null, 'deviceMoveQuery','Query move-wait','B07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0702', null, 'deviceMove','Move','B07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0703', null, 'deviceMoveRecordQuery','Query move-log','B07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0704', null, 'moveDel','Remove','B07','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B08', null, 'retainCard','RetainCard','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0801', null, 'cardQuery','Query','B08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0802', null, 'cardAdd','Add','B08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0803', null, 'cardDel','Remove','B08','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B09', null, 'atmLog','App log','B','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0901', null, 'logBackup','App-log download','B09','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B090101', null, 'logBackupQuery','Query','B0901','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0902', null, 'dayBackupJob','Daily back-up task','B09','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B090201', null, 'dayBackupJobQuery','Query','B0902','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B0904', null, 'atmLogInfo','Log back-up statistics','B09','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('B090401', null, 'atmLogInfoQuery','Query','B0904','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C', null, 'monitor','Monitor','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C01', null, 'monitor_device','StatusMonitor','C','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0101', null, 'remoteScreen','ScreenShot','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0102', null, 'takeLog','Get log','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0103', null, 'close','ShutDown','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0104', null, 'restart','Restart','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0105', null, 'logicOpen','OpenService','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0106', null, 'logicClose','StopService','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0107', null, 'remoteBrowser','Browse','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C010701', null, 'remoteUpFile','Upload','C0107','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C010702', null, 'remoteDownFile','Download','C0107','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0108', null, 'screenCamera','ScreenRecord','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0109', null, 'reset','ForceReset','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0110', null, 'modStatusGraphic','ModStatusGraphic','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0112', null, 'remoteCheckATM','AtmExamination','C01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C02', null, 'trans','TransMonitor','C','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0201', null, 'hits_trans','Query trans_History','C02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C020101', null, 'hitsTransQuery','Query','C0201','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0202', null, 'monitor_trans','TransMonitor','C02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0203', null, 'cash_init','CashAddQuery','C02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C020301', null, 'cashInitQuery','Query','C0203','1');


INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C0204', null, 'settlement','Settlement','C02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('C020401', null, 'settlementQuery','Query','C0204','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D', null, 'softDistribute','SoftDistribute','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D01', null, 'version','Version','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0101', null, 'versionQuery','Query','D01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0102', null, 'versionExportBtn','Issue','D01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0103', null, 'versionAdd','Add','D01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0104', null, 'versionUpdate','Modify','D01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0105', null, 'versionDel','Remove','D01','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D02', null, 'advert','Advertisement','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0201', null, 'advertQuery','Query','D02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0202', null, 'advertCreate','Create Advertisement','D02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D020201', null, 'advertWait','Create wait-insert-card adv','D0202','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D020202', null, 'advertTrans','Create transaction adv','D0202','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D020203', null, 'advertText','Create rolling-word adv','D0202','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D020204', null, 'advertAnnoucement','Announcement','D0202','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0203', null, 'advertDownAdvert','IssueAdvertisement','D02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0204', null, 'advertPreview','AdvertPreview','D02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0205', null, 'advertDel','Remove','D02','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D03', null, 'versionMonitor','VersionMonitor','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0301', null, 'versionMonitorQuery','Query','D03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0302', null, 'versionMonitorDel','Cancel job','D03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0303', null, 'exportJobToExcel','Export','D03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0304', null, 'resetStatus','Reset task status','D03','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D04', null, 'deviceVersion','DeviceVersion','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0401', null, 'deviceVersionQuery','Query','D04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D05', null, 'versionType','VersionType','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0501', null, 'versionTypeQuery','Query','D05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0502', null, 'versionTypeAdd','Add','D05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0503', null, 'versionTypeDel','Remove','D05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0504', null, 'versionTypeUpdate','Modify','D05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D06', null, 'versionAutoUpdate','VersionAutoUpdate','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D07', null, 'versionDistribute','VersionDistribute','D','0');



INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E', null, 'case','Fault','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E01', null, 'notifyMould','SMS content','E','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E02', null, 'faultConfig','FaultType setting','E','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E03', null, 'casefault','FaultSearch','E','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E04', null, 'casenotify','Query SMS','E','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E05', null, 'vendorCode','Manufacturer faultCode','E','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E0501', null, 'vendorCodeQuery','Query','E05','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E0502', null, 'vendorCodeImport','Batch import','E05','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('E0503', null, 'vendorCodeDelete','Batch delete','E05','1');


INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F', null, 'report','Report','0','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F01', null, 'basicReport','BasicReport','F','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0101', null, 'reportVendor','Device brand report','F01','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0102', null, 'reportDeviceBoxDetail','Cashbox left report','F01','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0103', null, 'reporDeviceHardWare','Hardware report','F01','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0104', null, 'reportDeviceUseCount','Device run report','F01','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0105', null, 'reportDeviceInfo','Device detail report','F01','0');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F02', null, 'transReport','TransReport','F','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0201', null, 'reportRetainCardDetail','Retain card detail report','F02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0202', null, 'reportRetainCardCount','Retain card report','F02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0203', null, 'reportTransactionCount','Transation report','F02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0204', null, 'reportTransactionResult','Transation result report','F02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0205', null, 'reportCashIn','CashAdd detail report','F02','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0206', null, 'reportSettlement','Clear report','F02','0');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F03', null, 'caseReport','FaultReport','F','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0301', null, 'caseTrendReportByMonth','Fault-trend chart(Month)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030101', null, 'exportToPngForMonth','ExportImage','F0301','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030102', null, 'exportToExcelForMonth','ExportExcel','F0301','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030103', null, 'exportToPdfForMonth','ExportPDF','F0301','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0302', null, 'caseTrendReportByDay','Fault-trend chart(Day)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030201', null, 'exportToPngForDay','ExportImage','F0302','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030202', null, 'exportToExcelForDay','ExportExcel','F0302','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030203', null, 'exportToPdfForDay','ExportPDF','F0302','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0303', null, 'caseStatisticsReportByBrand','Fault-count chart(Brand)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030301', null, 'exportToPngForBrand','ExportImage','F0303','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030302', null, 'exportToExcelForBrand','ExportExcel','F0303','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030303', null, 'exportToPdfForBrand','ExportPDF','F0303','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0304', null, 'caseStatisticsReportByDevice','Fault-count chart(Device)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030401', null, 'exportToPngForDevice','ExportImage','F0304','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030402', null, 'exportToExcelForDevice','ExportExcel','F0304','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030403', null, 'exportToPdfForDevice','ExportPDF','F0304','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0305', null, 'caseStatisticsReportByModule','Fault-count chart(Module)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030501', null, 'exportToPngForModule','ExportImage','F0305','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030502', null, 'exportToExcelForModule','ExportExcel','F0305','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030503', null, 'exportToPdfForModule','ExportPDF','F0305','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0306', null, 'caseStatisticsReportByCaseType','Fault-count chart(Type)','F03','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030601', null, 'exportToPngForType','ExportImage','F0306','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030602', null, 'exportToExcelForType','ExportExcel','F0306','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F030603', null, 'exportToPdfForType','ExportPDF','F0306','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F04', null, 'openRateReport','OpernRate','F','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0401', null, 'deviceOpenRate','OpernRate_Device','F04','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0402', null, 'typeOpenRate','OpernRate_Type','F04','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F0403', null, 'orgOpenRate','OpernRate_Org','F04','0');
INSERT INTO SM_ORG(ID,ADDRESS,CODE,DESCRIPTION,NAME,ORG_FLAG,STATE,ORG_TYPE,PERSON_ID,ZIP,PARENT_ID) VALUES ('1', null, 'root', null, 'Org', '-1', null, null, '0', null, null);
INSERT INTO SM_ORG(CODE,NAME,ORG_FLAG,STATE,ORG_TYPE,PERSON_ID,PARENT_ID) VALUES('YIHUA','YIHUASHENZHEN','-2-1',1,1,0,1);

INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('1', '0000', 'Chairman','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('2', '0001', 'President(RootBank)','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('3', '0002', 'Manager','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('4', '0003', 'ViceManager','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('5', '0004', 'President(BranchBank)','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('6', '0005', 'SectionChief','');
INSERT INTO SM_PERSON_JOB(ID,CODE,NAME,REMARK) VALUES('7', '0006', 'Accounting','');

INSERT INTO SM_PERSON(ID,BIRTHDAY,CODE,EMAIL,GENDER,MOBILE,NAME,PHONE,PERSON_TYPE,ORGANIZATION_ID,PERSONJOB) VALUES ('1', '2012-04-13', 'Super manager', '', '0', '15855772942', 'admin', '1859999', null, '1', '1');

INSERT INTO SM_ROLE(PM_ROLE_ID,RELATION,NOTE,INHERIT,NAME,IS_SYSTEM,ROLE_TYPE) VALUES ('1', '', 'Default sys-super-manager', '', 'Super manager', 1, '0');

 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('0','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A01','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0101','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0102','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0103','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0104','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0105','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0106','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A02','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0201','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0202','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0203','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0204','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0205','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A03','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0301','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0302','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0303','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0304','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0305','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A04','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0401','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0402','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0403','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0404','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0405','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A05','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0501','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0502','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0503','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0504','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A07','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A08','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0801','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0802','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0803','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0804','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A09','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0901','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A0902','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('A10','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B01','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0101','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0102','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0103','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0104','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B02','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0201','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B03','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0301','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0302','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0303','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0304','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B04','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0401','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0402','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0403','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0404','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B05','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0501','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0502','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0503','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0504','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0505','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0506','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0507','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B06','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0601','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0602','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0603','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0604','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B07',  '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0701','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0702','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0703','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0704','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B08', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0801','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0802','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0803','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B09', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0901', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B090101','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0902','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B090201','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B0904', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('B090401','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C01','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0101', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0102', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0103', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0104', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0105',  '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0106', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0107', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C010701','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C010702','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0108', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0109','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0110','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0112','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C02', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0201', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C020101','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0202', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0203', '1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C020301','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C0204','1');
 INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('C020401','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D01','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0101','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0102','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0103','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0104','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0105','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0106','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0107','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0108','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D02','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0201','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0202','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D020201','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D020202','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D020203','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D020204','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0203','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0204','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0205','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D03','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0301','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0302','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0303','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0304','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D04','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0401','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D05','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0501','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0502','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0503','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0504','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D06','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D07','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E01','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E02','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E03','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E04','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E05','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E0501','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E0502','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('E0503','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F01','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0101','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0102','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0103','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0104','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0105','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F02','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0201','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0202','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0203','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0204','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0205','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0206','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F03','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0301','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030101','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030102','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030103','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0302','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030201','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030202','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030203','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0303','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030301','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030302','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030303','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0304','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030401','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030402','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030403','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0305','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030501','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030502','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030503','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0306','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030601','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030602','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F030603','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F04','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0401','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0402','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F0403','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('Z','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('Z01','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('Z02','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('Z03','1');



INSERT INTO SM_USER(ID,ACCESS_COUNT,CODE,ENABLED,FREEZE_TIME,ACCESS_TIME,LOGIN_FAIL_COUNT,PWD,PERSON_ID,IS_SYSTEM,STATE,USER_TYPE) VALUES ('1', '4', 'admin', '1', null,null, '0', '21232f297a57a5a743894a0e4a801fc3', '1', '0', '1',1);

INSERT INTO SM_USER_ROLE(USER_ROLE_ID,ROLE_ID,USER_ID) VALUES ('1', '1', '1');



INSERT INTO DEV_VENDOR(COUNTRY,HOTLINE1,NAME,STATUS) VALUES('ChineseShenzheng','02512345678','Yihua',0);

INSERT INTO DEV_TYPE(CASHTYPE,NAME,DEV_CATALOG_ID,DEV_VENDOR_ID) VALUES(0,'CDS6040W',2,1);
INSERT INTO DEV_TYPE(CASHTYPE,NAME,DEV_CATALOG_ID,DEV_VENDOR_ID) VALUES(0,'CDS6040T',2,1);


/*内置的软件分类**/
INSERT INTO VER_VERSION_TYPE(ID,TYPE_NAME,IS_DISPLAY,IS_SYSTEM,CUSTOM_VERSION,REMARK,DEFAULT_INSTALL_PATH,VERSION_CATALOG) VALUES ('1','advert','0','1','0','内置广告类型','C:/yihua/gump/installation','ADVERT');
INSERT INTO VER_VERSION_TYPE(ID,TYPE_NAME,IS_DISPLAY,IS_SYSTEM,CUSTOM_VERSION,REMARK,DEFAULT_INSTALL_PATH,VERSION_CATALOG) VALUES ('2', 'gump-professional','1','1','1','C端应用二代','C:/yihua/gump/installation','APP');



INSERT INTO CASE_FAULT_CLASSIFY(ID, CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES('N_AP_STAT','ATMC status changed','ADMIN',0.0,0,1,'SMS');
INSERT INTO CASE_FAULT_CLASSIFY(ID, CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES('N_AP_SETUP','Sys init intall','ADMIN',0.0,0,1,'SMS');
INSERT INTO CASE_FAULT_CLASSIFY(ID, CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES('F_MOD','HardwareError','ADMIN',0.0,0,1,'SMS');
INSERT INTO CASE_FAULT_CLASSIFY(ID, CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES('R_CASSET','CashEmpty','ADMIN',0.0,0,1,'SMS');
INSERT INTO CASE_FAULT_CLASSIFY(ID, CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES('R_PTR','PaperLow','ADMIN',0.0,0,1,'SMS');

INSERT INTO CASE_FAULT_CLASSIFY(ID,CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES ('R_CIM', 'CashFull', 'ADMIN', 0.0, 0, 1, 'SMS');
INSERT INTO CASE_FAULT_CLASSIFY(ID,CLASSIFY_NAME,RESPONSOR_TYPE,RESOLVE_HOUR,UPGREAD,NOTIFY_TIMES,NOTIFY_WAY) VALUES ('R_CDM', 'CashLow', 'ADMIN', 0.0, 0, 1, 'SMS');



INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('N_AP_STAT','CREATE','SMS','Please pay attention{terminalId}{faultClassify}{appStatus},Sen by monitor system');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('N_AP_SETUP','CREATE','SMS','Please pay attention{terminalId}{faultClassify},Sen by monitor system');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('F_MOD','CREATE','SMS','Please pay attention{terminalId}{faultClassify}{faultMod},Sen by monitor system');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('R_CASSET','CREATE','SMS','Please pay attention{terminalId}{faultClassify},Sen by monitor system');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('R_PTR','CREATE','SMS','Please pay attention{terminalId}{faultClassify}{faultMod},Sen by monitor system');

INSERT INTO ATMC_TRANS_TYPE(TRANS_CODE,CODE_DESC,TRANS_SEQ)VALUES('DEP','Deposit',1);
INSERT INTO ATMC_TRANS_TYPE(TRANS_CODE,CODE_DESC,TRANS_SEQ)VALUES('INQ','Query',2);
INSERT INTO ATMC_TRANS_TYPE(TRANS_CODE,CODE_DESC,TRANS_SEQ)VALUES('PIN','Password',3);
INSERT INTO ATMC_TRANS_TYPE(TRANS_CODE,CODE_DESC,TRANS_SEQ)VALUES('TFR','Transfer',4);
INSERT INTO ATMC_TRANS_TYPE(TRANS_CODE,CODE_DESC,TRANS_SEQ)VALUES('CWD','Draw',5);

