CREATE TABLE SM_ORG (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS VARCHAR(60) DEFAULT NULL,
  CODE VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(40) DEFAULT NULL,
  NAME VARCHAR(40) NOT NULL,
  ORG_FLAG VARCHAR(100) DEFAULT NULL,
  STATE INT(11) DEFAULT NULL,
  ORG_TYPE INT(11) DEFAULT NULL,
  PERSON_ID BIGINT(20) DEFAULT NULL,
  ZIP VARCHAR(20) DEFAULT NULL,
  PARENT_ID BIGINT(20) DEFAULT NULL,
  SERVICE_OBJECT BIGINT(20) DEFAULT NULL,
  ORG_LEVEL INT(11) DEFAULT NULL,
  AREA_FLAG VARCHAR(24) DEFAULT NULL,
  IS_NOTE_SEND VARCHAR(2) DEFAULT NULL,
  SUGGEST VARCHAR(120) DEFAULT NULL,
  LEGAL_PER_CODE VARCHAR(10) DEFAULT NULL,
  APPLICATION_PER  VARCHAR(24) DEFAULT NULL ,
  PRIMARY KEY (ID),
  FOREIGN KEY (PARENT_ID) REFERENCES SM_ORG (ID)
);

CREATE TABLE SM_ANNOUNCEMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ATTACHMENT VARCHAR(128) DEFAULT NULL,
  CONTENT VARCHAR(3000) NOT NULL,
  ENDDATE DATE DEFAULT NULL,
  PUBLISHDATE DATE NOT NULL,
  PUBLISHER VARCHAR(20) NOT NULL,
  THEME VARCHAR(64) NOT NULL,
  RELEASEDATE DATE DEFAULT NULL,
  RELEASEPERSON VARCHAR(20) DEFAULT NULL,
  ANNOUNCESTATUS BIGINT DEFAULT NULL,
  PUBLISHERORG BIGINT DEFAULT  NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SM_ANNOUNCEMENT_ORG(
	ANNOUNCE_ORG_ID BIGINT(20) NOT NULL,
	ANNOUNCEMETN_ID BIGINT NOT NULL,
	ORG_ID BIGINT NOT NULL,
	PRIMARY KEY (ANNOUNCE_ORG_ID)
);

CREATE TABLE SM_PARAM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARAM_CLASSIFY INT(11) DEFAULT NULL,
  DESCIPTION VARCHAR(60) DEFAULT NULL,
  PARAM_KEY VARCHAR(20) DEFAULT NULL,
  PARAM_VALUE VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SM_PERMISSION (
  PERMISSION_ID VARCHAR(20) NOT NULL,
  PER_ACTION VARCHAR(40) DEFAULT NULL,
  CODE VARCHAR(40) DEFAULT NULL,
  DESCRIPTION VARCHAR(40) DEFAULT NULL,
  PARENT_ID VARCHAR(20) DEFAULT NULL,
  IS_BUTTON CHAR(1) DEFAULT '0',
  PRIMARY KEY (PERMISSION_ID),
  UNIQUE KEY CODE (CODE),
  FOREIGN KEY (PARENT_ID) REFERENCES SM_PERMISSION (PERMISSION_ID)
);

CREATE TABLE SM_PERSON_JOB (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(20) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  REMARK VARCHAR(400) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SM_PERSON (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  JOB_NUM VARCHAR(40) DEFAULT NULL,
  BIRTHDAY DATE DEFAULT NULL,
  CODE VARCHAR(40) DEFAULT NULL,
  EMAIL VARCHAR(50) DEFAULT NULL,
  GENDER INT(11) DEFAULT NULL,
  MOBILE VARCHAR(20) DEFAULT NULL,
  NAME VARCHAR(40) NOT NULL,
  PHONE VARCHAR(20) DEFAULT NULL,
  STATE INT(11) DEFAULT NULL,
  PERSON_TYPE INT(11) DEFAULT NULL,
  ORGANIZATION_ID BIGINT(20) DEFAULT NULL,
  REMARK VARCHAR(400) DEFAULT NULL,
  PERSONJOB BIGINT(20) DEFAULT NULL,
  RESERVE1 VARCHAR(20) DEFAULT NULL,
  RESERVE2 VARCHAR(20) DEFAULT NULL,
  RESERVE3 VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANIZATION_ID) REFERENCES SM_ORG (ID),
  FOREIGN KEY (PERSONJOB) REFERENCES SM_PERSON_JOB (ID)
);


CREATE TABLE SM_ROLE (
  PM_ROLE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  RELATION BIT(1) DEFAULT NULL,
  NOTE VARCHAR(300) DEFAULT NULL,
  INHERIT BIT(1) DEFAULT NULL,
  NAME VARCHAR(40) NOT NULL,
  IS_SYSTEM BIT(1) DEFAULT NULL,
  ROLE_TYPE INT(11) DEFAULT NULL,
  PRIMARY KEY (PM_ROLE_ID)
);

CREATE TABLE SM_ROLE_PERMISSION (
  ROLE_PERMISSION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PERMISSION_ID VARCHAR(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ROLE_PERMISSION_ID)
);

CREATE TABLE SM_USER_PERMISSION(
	USER_PERMISSION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	PERMISSION_ID VARCHAR(20) NOT NULL,
	USER_ID BIGINT(20) NOT NULL,
	PRIMARY KEY (USER_PERMISSION_ID)
);

CREATE TABLE SM_USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ACCESS_COUNT INT(11) NOT NULL,
  CODE VARCHAR(40) NOT NULL,
  ENABLED CHAR(1) DEFAULT NULL,
  FREEZE_TIME DATETIME DEFAULT NULL,
  ACCESS_TIME DATETIME DEFAULT NULL,
  LOGIN_FAIL_COUNT INT(11) NOT NULL,
  PWD VARCHAR(40) NOT NULL,
  PERSON_ID VARCHAR(20) NOT NULL,
  IS_SYSTEM CHAR(1) NOT NULL,
  STATE INT(11) NOT NULL,
  CHECK_REMARK VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY CODE (CODE)
);

CREATE TABLE SM_USER_ROLE (
  USER_ROLE_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ROLE_ID BIGINT(20) DEFAULT NULL,
  USER_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID)
);

CREATE TABLE SM_USER_LOG (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  OPER_TIME TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  OPER_CODE VARCHAR(40) NOT NULL,
  OPER_NAME VARCHAR(40) NOT NULL,
  OPER_CONTENT VARCHAR(100) NOT NULL,
  OPER_RESULT VARCHAR(10) NOT NULL,
  PRIMARY KEY  (ID)
);

CREATE TABLE SM_JOB_SYNCHRON (
  ID VARCHAR(40) NOT NULL,
  JOB_NAME VARCHAR(40),
  JOB_TRIGER VARCHAR(40),
  SERVER_IP VARCHAR(40),
  JOB_DATE TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY  (ID)
);


CREATE TABLE DEV_CATALOG (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) DEFAULT NULL,
  CATALOG_NO VARCHAR(5) DEFAULT NULL,
  NOTE VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DEV_GROUP (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) DEFAULT NULL,
  NOTE VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DEV_EXTEND (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  BUY_DATE DATE DEFAULT NULL,
  CARRIER VARCHAR(20) DEFAULT NULL,
  CLOSE_TIME VARCHAR(10) DEFAULT NULL,
  COST_INTEREST VARCHAR(50) DEFAULT NULL,
  DECORATION DOUBLE(11,2) DEFAULT NULL,
  DECORATION_COST DOUBLE(11,2) DEFAULT NULL,
  DEPRECIATION_LIFE DOUBLE(11,2) DEFAULT NULL,
  EXPIRE_DATE DATE DEFAULT NULL,
  EXPIRE_PM_DATE DATE DEFAULT NULL,
  GOVERNANCE_COST DOUBLE(11,2) DEFAULT NULL,
  GOVERNANCE_RENT DOUBLE(11,2) DEFAULT NULL,
  INSTALL_DATE DATE DEFAULT NULL,
  LAST_PM_DATE DATE DEFAULT NULL,
  MONEY_COST DOUBLE(11,2) DEFAULT NULL,
  MONEY_ORG VARCHAR(20) DEFAULT NULL,
  NET_COST DOUBLE(11,2) DEFAULT NULL,
  NET_TYPE INT(11) DEFAULT NULL,
  OPEN_TIME VARCHAR(10) DEFAULT NULL,
  PATROL_PERIOD INT(11) DEFAULT NULL,
  POWER_COST DOUBLE(11,2) DEFAULT NULL,
  PRICE DOUBLE(11,2) DEFAULT NULL,
  SERIAL VARCHAR(40) DEFAULT NULL,
  START_DATE DATE DEFAULT NULL,
  STOP_DATE DATE DEFAULT NULL,
  TEMINAL_ID VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY TEMINAL_ID (TEMINAL_ID)
);

CREATE TABLE DEV_VENDOR (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS VARCHAR(60) DEFAULT NULL,
  COUNTRY VARCHAR(30) DEFAULT NULL,
  HOTLINE1 VARCHAR(20) DEFAULT NULL,
  HOTLINE2 VARCHAR(20) DEFAULT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  STATUS INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DEV_TYPE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CASHTYPE INT(11) DEFAULT NULL,
  NAME VARCHAR(30) DEFAULT NULL,
  SPEC VARCHAR(20) DEFAULT NULL,
  WATT VARCHAR(20) DEFAULT NULL,
  WEIGHT VARCHAR(20) DEFAULT NULL,
  DEV_CATALOG_ID BIGINT(20) DEFAULT NULL,
  DEV_VENDOR_ID BIGINT(20) DEFAULT NULL,
  REMARK VARCHAR(150) DEFAULT NULL,
  TYPE_STATUS BIGINT DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (DEV_VENDOR_ID) REFERENCES DEV_VENDOR (ID),
  FOREIGN KEY (DEV_CATALOG_ID) REFERENCES DEV_CATALOG (ID)
);

CREATE TABLE DEV_INFO (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS VARCHAR(50) DEFAULT NULL,
  ATMC_APP VARCHAR(50) DEFAULT NULL,
  AWAY_FLAG VARCHAR(15) DEFAULT NULL,
  CARE_LEVEL VARCHAR(15) DEFAULT NULL,
  CASH_TYPE VARCHAR(10) DEFAULT NULL,
  CASHBOX_LIMIT INT(11) DEFAULT NULL,
  IP VARCHAR(20) DEFAULT NULL,
  SETUP_TYPE VARCHAR(10) DEFAULT NULL,
  ATM_SP VARCHAR(50) DEFAULT NULL,
  STATUS INT(11) DEFAULT NULL,
  TERMINAL_ID VARCHAR(20) DEFAULT NULL,
  WORK_TYPE VARCHAR(16) DEFAULT NULL,
  DEV_SERVICE_ID BIGINT(20) DEFAULT NULL,
  DEV_TYPE_ID BIGINT(20) DEFAULT NULL,
  DEVICE_EXTEND_ID BIGINT(20) NOT NULL,
  ORG_ID BIGINT(20) DEFAULT NULL,
  VIRTUAL VARCHAR(25) DEFAULT NULL,
  MAC VARCHAR(50) DEFAULT NULL,
  VIDEO_TYPE VARCHAR(4) DEFAULT NULL,
  APPLY_ID BIGINT DEFAULT NULL,
  APPLY_TIME DATE DEFAULT NULL,
  AUDITER_ID BIGINT DEFAULT NULL,
  AUD_TIME DATE DEFAULT NULL,
  PLACE_TYPE VARCHAR(10) DEFAULT NULL,
  APPLY_REMARK VARCHAR(250) DEFAULT NULL,
  AUDITER_REMARK VARCHAR(250) DEFAULT NULL,
  CHECK_STATUS INTEGER DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY DEVICE_EXTEND_ID (DEVICE_EXTEND_ID),
  UNIQUE KEY TERMINAL_ID (TERMINAL_ID),
  FOREIGN KEY (DEV_TYPE_ID) REFERENCES DEV_TYPE (ID),
  FOREIGN KEY (DEV_SERVICE_ID) REFERENCES SM_ORG (ID),
  FOREIGN KEY (ORG_ID) REFERENCES SM_ORG (ID),
  FOREIGN KEY (DEVICE_EXTEND_ID) REFERENCES DEV_EXTEND (ID),
  FOREIGN KEY (APPLY_ID) REFERENCES SM_USER (ID),
  FOREIGN KEY (AUDITER_ID) REFERENCES SM_USER (ID)
);

CREATE TABLE DEV_MODULE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(5) DEFAULT NULL,
  MOD_NO VARCHAR(5) DEFAULT NULL,
  NOTE VARCHAR(100) DEFAULT NULL,
  IS_CASE CHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DEV_PERSON (
  DEV_PERSON_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DEV_ID BIGINT(20) DEFAULT NULL,
  PERSON_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (DEV_PERSON_ID)
);

CREATE TABLE DEV_GROUP_RELATION (
  DEV_GROUP_RELATION_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DEV_ID BIGINT(20) DEFAULT NULL,
  GROUP_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (DEV_GROUP_RELATION_ID)
);
