--默认增加的人员类型为普通用户
ALTER TABLE SM_USER ADD  USER_TYPE INT(5) DEFAULT 1;
ALTER TABLE VER_DEVICE_SOFT_VERSION ADD  VERSION_STR VARCHAR(40) DEFAULT NULL;
ALTER TABLE VER_VERSION ADD  VERSION_STR VARCHAR(40) DEFAULT NULL;