--默认增加的人员类型为普通用户
ALTER TABLE SM_USER ADD  USER_TYPE INT(5) DEFAULT 1;
ALTER TABLE VER_DEVICE_SOFT_VERSION ADD  VERSION_STR VARCHAR(40) DEFAULT NULL;
ALTER TABLE VER_VERSION ADD  VERSION_STR VARCHAR(40) DEFAULT NULL;

ALTER TABLE VER_VERSION ADD  DOWNLOAD_COUNTER INT(10) DEFAULT 1;
ALTER TABLE VER_TASK ADD FIRST_TIME DATETIME DEFAULT NULL;
ALTER TABLE VER_TASK ADD TASK_COUNT BIGINT(20) DEFAULT 1;
ALTER TABLE VER_TASK ADD BATCH_NAME VARCHAR(20) DEFAULT NULL;
ALTER TABLE VER_DEVICE_SOFT_VERSION CHANGE TERMINAL_ID DEVICE_ID BIGINT(20) NOT NULL;
--以下三行非注释，请勿删除-------------------------------------------------------
--此处要查询外键名称 show create table ver_task ;
--ALTER TABLE VER_TASK drop FOREIGN KEY
--ALTER TABLE VER_TASK drop JOB_ID ;
DROP TABLE VER_JOB;
DROP TABLE VER_DEVICE_SOFT_VERSION;

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D06', null, 'versionAutoUpdate','自动更新信息','D','0');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D06','1');


INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D07', null, 'versionDistribute','版本分布图','D','0');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D07','1');

INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE) VALUES ('10', '1', '故障处理并发数', 'status_handle_count', '30');

ALTER TABLE CASE_FAULT ADD CLOSE_TYPE VARCHAR(20);


CREATE TABLE TEMP_DEV_INFO (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS VARCHAR(128) DEFAULT NULL,
  AWAY_FLAG VARCHAR(15) DEFAULT NULL,
  CASHBOX_LIMIT INT(11) DEFAULT NULL,
  IP VARCHAR(20) DEFAULT NULL,
  SETUP_TYPE VARCHAR(10) DEFAULT NULL,
  STATUS INT(11) DEFAULT NULL,
  TERMINAL_ID VARCHAR(20) DEFAULT NULL,
  WORK_TYPE VARCHAR(16) DEFAULT NULL,
  DEV_SERVICE_ID BIGINT(20) DEFAULT NULL,
  DEV_TYPE_ID BIGINT(20) DEFAULT NULL,
  ORG_ID BIGINT(20) DEFAULT NULL,
  VIRTUAL VARCHAR(25) DEFAULT NULL,
  MAC VARCHAR(50) DEFAULT NULL,
  NET_TYPE INT(11) DEFAULT NULL,
  SERIAL VARCHAR(40) DEFAULT NULL,
  INSTALL_DATE DATE DEFAULT NULL,
  EFFECTIVE_DATE DATE DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY TERMINAL_ID (TERMINAL_ID),
  FOREIGN KEY (DEV_TYPE_ID) REFERENCES DEV_TYPE (ID),
  FOREIGN KEY (DEV_SERVICE_ID) REFERENCES SM_ORG (ID),
  FOREIGN KEY (ORG_ID) REFERENCES SM_ORG (ID)
);