alter table PARAM_PUBLISH add column PUBLISHER_TYPE int default 1;

INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE,PARAM_TYPE) VALUES ('13', '0', '参数发布并发数', 'param_update_count', '30','系统配置');
CREATE TABLE PARAM_PUBLISH_APP_RESULT(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	APP_SYSTEM_ID BIGINT(20) NOT NULL,
	PARAM_PUBLISH_RESULT_ID BIGINT(20) NOT NULL,
	STATUS VARCHAR(15) DEFAULT NULL,
	REASON VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;