ALTER TABLE SM_USER_LOG ADD COLUMN CLIENT_IP varchar(20) DEFAULT null;
ALTER TABLE SM_USER_LOG ADD COLUMN SERVER_IP varchar(20) DEFAULT null;
ALTER TABLE SM_USER_LOG ADD COLUMN TIMES BIGINT(20) DEFAULT 0;

