--应用系统表
CREATE TABLE PARAM_APP_SYSTEM(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR (40) NOT NULL,
  SETTING_FILE_PATH VARCHAR (80) NOT NULL, 
  SETTING_FILE_NAME VARCHAR (40) NOT NULL, 
  SETTING_FILE_FORMAT VARCHAR (60) NOT NULL, 
  REMARK VARCHAR (40) ,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--参数元数据表
CREATE TABLE PARAM_ELEMENT(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CREATE_TIME DATETIME DEFAULT NULL,
  LAST_MODIFY_TIME DATETIME DEFAULT NULL,
  PARAM_NAME VARCHAR (40) NOT NULL,
  PARAM_VALUE VARCHAR (40) NOT NULL,
  PARAM_TYPE VARCHAR (10) ,
  PARAM_CLASSIFY VARCHAR (10),
  VERSION_NO VARCHAR(60),
  PARAM_RIGHTS VARCHAR(10),
  PARAM_BELONGS VARCHAR(40), 
  REMARK VARCHAR (60),
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--参数模板表
CREATE TABLE PARAM_TEMPLATE(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30), 
  REMARK VARCHAR (60),
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--模板-参数关联表
CREATE TABLE PARAM_TEMPLATE_EMLEMT_RELATION(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TEMPLATE_ID BIGINT(20), 
  EMLEMT_ID BIGINT(20), 
  REMARK VARCHAR (60),
  PRIMARY KEY (ID),
  FOREIGN KEY (TEMPLATE_ID) REFERENCES PARAM_TEMPLATE(ID),
  FOREIGN KEY (EMLEMT_ID) REFERENCES PARAM_ELEMENT(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--模板-设备关联表
CREATE TABLE PARAM_TEMPLATE_DEVICE_RELATION(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  TEMPLATE_ID BIGINT(20), 
  DEVICE_ID BIGINT(20), 
  PRIMARY KEY (ID),
  FOREIGN KEY (TEMPLATE_ID) REFERENCES PARAM_TEMPLATE(ID),
  FOREIGN KEY (DEVICE_ID) REFERENCES DEV_INFO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--参数-设备版本表
CREATE TABLE PARAM_DEVICE_VERSION(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DEVICE_ID BIGINT(20), 
  PARAM_ID BIGINT(20),
  PRIMARY KEY (ID),
  FOREIGN KEY (DEVICE_ID) REFERENCES DEV_INFO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--参数-设备关联表
CREATE TABLE PARAM_DEVICE_RELATION(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  DEVICE_ID BIGINT(20), 
  PARAM_ELEMENT BIGINT(20),
  PRIMARY KEY (ID),
  FOREIGN KEY (DEVICE_ID) REFERENCES DEV_INFO(ID),
  FOREIGN KEY (PARAM_ELEMENT) REFERENCES PARAM_ELEMENT(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--参数分类表
CREATE TABLE PARAM_CLASSIFY(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(40),
  REMARK VARCHAR(40),
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;