
CREATE TABLE ADV_GROUP (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT(20) NOT NULL,
  GROUP_NAME VARCHAR(60) NOT NULL,
  GROUP_TYPE VARCHAR(20) NOT NULL,
  RESOURCE_PATH  VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE ADV_GROUP_DEVICE_RELATION (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  GROUP_ID BIGINT(20) NOT NULL,
  DEVICE_ID BIGINT(20) NOT NULL,
  ADVERT_ID BIGINT(20) NOT NULL,
  ADVERT_ID_USING BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE ADV_BSADVERT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  GROUP_ID BIGINT(20) NOT NULL,
  ADVERT_NAME VARCHAR(60) NOT NULL,
  ADVERT_STRATUS INT(1) DEFAULT NULL,
  LAST_TIME DATETIME NOT NULL,
  ADVERT_TYPE VARCHAR(32) NOT NULL,
  USER_ID BIGINT(20) DEFAULT NULL,
  ACTIVE_USER_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE ADV_BSADVERT_RESOURCE(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  BEGIN_DATE DATE DEFAULT NULL,
  BEGIN_TIME VARCHAR(32) DEFAULT NULL,
  CONTENT VARCHAR(140) DEFAULT NULL,
  END_DATE DATE DEFAULT NULL,
  END_TIME VARCHAR(32) DEFAULT NULL,
  PLAY_TIME INT(11) DEFAULT NULL,
  ADVERT_ID BIGINT(20) DEFAULT NULL,
  SCREEN VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ADVERT_ID) REFERENCES ADV_BSADVERT (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE INDEX IDX_ADV_BSADVERT_RESOURCE_1 ON ADV_BSADVERT_RESOURCE(ADVERT_ID);
CREATE INDEX IDX_ADV_BSADVERT_1 ON ADV_BSADVERT(GROUP_ID);
CREATE INDEX IDX_ADV_GROUP_DEVICE_RELATION_1 ON ADV_GROUP_DEVICE_RELATION(GROUP_ID);
CREATE INDEX IDX_ADV_GROUP_DEVICE_RELATION_2 ON ADV_GROUP_DEVICE_RELATION(DEVICE_ID);


INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE,PARAM_TYPE) VALUES ('12', '0', 'BS广告服务器路径', 'bsAdvertServerPath', 'D:\\tomcat\\webapps\\ROOT\\advert','BS广告配置');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D07', null, 'bsAdvertGroup','BS广告组管理','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0701', null, 'bsAdvertGroupQuery','查询','D07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0702', null, 'bsAdvertGroupCreate','增加广告组','D07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0703', null, 'bsAdvertGroupUpdate','更改广告组','D07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0704', null, 'bsAdvertGroupDel','删除广告组','D07','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0705', null, 'bsAdvertGroupLinkDevice','关联设备','D07','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D08', null, 'bsAdvert','BS广告管理','D','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0801', null, 'bsAdvertQuery','BS广告查询','D08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0802', null, 'bsAdvertAdd','BS广告增加','D08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0803', null, 'bsAdvertUpdate','BS广告更改','D08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0804', null, 'bsAdvertDel','BS广告删除','D08','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('D0805', null, 'bsAdvertActive','BS广告激活','D08','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D07','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0701','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0702','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0703','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0704','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0705','1');


INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D08','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0801','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0802','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0803','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0804','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('D0805','1');
