
ALTER TABLE DEV_BOX_INFO ADD COLUMN CASHIN_VALUE BIGINT(20) DEFAULT 0;
ALTER TABLE DEV_BOX_INFO ADD COLUMN BILL_VALUE BIGINT(20) DEFAULT 0;

ALTER TABLE ATMC_TRANS_TYPE ADD COLUMN IN_OUT_FLAG INT(1) DEFAULT 0;

CREATE TABLE DEV_BOX_INIT_RULE
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	RULE_DESC VARCHAR(100) NOT NULL,
	START_USING CHAR(1) DEFAULT '1',
	RULE_TYPE VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO DEV_BOX_INIT_RULE VALUES(1,'钞箱阈值预警','根据钞箱的阈值进行预警加钞','1');
INSERT INTO DEV_BOX_INIT_RULE VALUES(2,'加钞间隔预警','根据上次加钞至今时间间隔预警加钞','1');


INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE,PARAM_TYPE) VALUES ('17', '1', '加钞间隔预警', 'cashinit_days', '7', '钞箱预警');
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE,PARAM_TYPE) VALUES ('18', '0', '加钞机构级别', 'cashinit_orglevel', '2', '钞箱预警');


CREATE TABLE ATMC_DAY_TRADING_VOLUME
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	TERMINAL_ID VARCHAR(100) NOT NULL,
	TRANS_DATE INT(8) NOT NULL,
	AMT_IN BIGINT(20) NOT NULL,
	AMT_OUT BIGINT(20) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE ATMC_MONTH_TRADING_VOLUME
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	MONTH_IN_AVG BIGINT(20) NOT NULL,
	MONTH_OUT_AVG BIGINT(20) NOT NULL,
	TERMINAL_ID VARCHAR(100) NOT NULL,
	TRANS_MONTH INT(8) NOT NULL,
	LAST_YEAR_IN_AVG BIGINT(20) NOT NULL,
	LAST_YEAR_OUT_AVG BIGINT(20) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE DEV_CASH_INIT_PLAN
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	PLAN_DATE INT(10) NOT NULL,
	CASH_INIT_CODE VARCHAR(20) NOT NULL,
	ORG_ID BIGINT(20) NOT NULL,
	CASH_INIT_PLAN_AMT BIGINT(20) NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE DEV_CASH_INIT_PLAN_DEVICE
(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	TERMINAL_ID VARCHAR(20) NOT NULL,
	ORG_NAME VARCHAR(40) NOT NULL,
	LAST_AMT BIGINT(20) DEFAULT NULL,
	AWAY_FLAG VARCHAR(20) DEFAULT NULL,
	DEV_TYPE VARCHAR(30) DEFAULT NULL,
	LAST_DATE VARCHAR(20) DEFAULT NULL,
	ADVICE_AMT BIGINT(20) NOT NULL,
	ACTUAL_AMT BIGINT(20) NOT NULL,
	INIT_FLAG INT(1) NOT NULL,
	ADDRESS VARCHAR(60) DEFAULT NULL,
	CASH_INIT_PLAN_ID BIGINT(20) DEFAULT NULL,
	CASH_INIT CHAR(1) DEFAULT '1',
	PRIMARY KEY (ID),
    FOREIGN KEY (CASH_INIT_PLAN_ID) REFERENCES DEV_CASH_INIT_PLAN (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE ATMC_CASH_INIT_UNIQUE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  AMT BIGINT(20) DEFAULT NULL,
  CASH_DATE VARCHAR(20) DEFAULT NULL,
  TERMINAL_ID VARCHAR(20) NOT NULL,
  UUID VARCHAR(20) DEFAULT NULL,
  UNIQUE (TERMINAL_ID),
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;