INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('N_AP_STAT','CREATE','MAIL','请关注{terminalId}{faultClassify}{appStatus},标准化监控发送');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('N_AP_SETUP','CREATE','MAIL','请关注{terminalId}{faultClassify},标准化监控发送');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('F_MOD','CREATE','MAIL','请关注{terminalId}{faultClassify}{faultMod},标准化监控发送');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('R_CASSET','CREATE','MAIL','请关注{terminalId}{faultClassify},标准化监控发送');
INSERT INTO CASE_NOTIFY_MOULD(CLASSIFY_ID,NOTIFY_TYPE,NOTIFY_WAY,NOTIFY_SET) VALUES('R_PTR','CREATE','MAIL','请关注{terminalId}{faultClassify}{faultMod},标准化监控发送');


--将广告设置于为自动部署(主要是进行通知应用)
UPDATE VER_VERSION_TYPE SET AUTO_DEPLOY = '1' WHERE  ID =1;
UPDATE SM_PERMISSION SET DESCRIPTION='通知查询' where PERMISSION_ID='E02';
UPDATE SM_PERMISSION SET DESCRIPTION='通知内容配置' where PERMISSION_ID='E01';