UPDATE SM_PERMISSION SET ICON_CLS = 'menu-system' WHERE PERMISSION_ID = 'A';
UPDATE SM_PERMISSION SET ICON_CLS = 'menu-device' WHERE PERMISSION_ID = 'B';
UPDATE SM_PERMISSION SET ICON_CLS = 'menu-monitor' WHERE PERMISSION_ID = 'C';
UPDATE SM_PERMISSION SET ICON_CLS = 'menu-application' WHERE PERMISSION_ID = 'D';
UPDATE SM_PERMISSION SET ICON_CLS = 'menu-faults' WHERE PERMISSION_ID = 'E';
UPDATE SM_PERMISSION SET ICON_CLS = 'menu-reports' WHERE PERMISSION_ID = 'F';