alter table PARAM_PUBLISH add column PUBLISHER_TYPE int default 1;

alter table PARAM_PUBLISH add column TEMPLATE_ID BIGINT(20) DEFAULT 0;

alter TABLE PARAM_DEVICE_DETAIL modify PARAM_VALUE VARCHAR (128) NOT NULL;
INSERT INTO SM_PARAM(ID,PARAM_CLASSIFY,DESCIPTION,PARAM_KEY,PARAM_VALUE,PARAM_TYPE) VALUES ('13', '0', '参数发布并发数', 'param_update_count', '30','系统配置');
CREATE TABLE PARAM_PUBLISH_APP_RESULT(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	APP_SYSTEM_ID BIGINT(20) NOT NULL,
	PARAM_PUBLISH_RESULT_ID BIGINT(20) NOT NULL,
	STATUS VARCHAR(15) DEFAULT NULL,
	REASON VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G04',NULL,'devParameter','设备参数管理','G','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0401',NULL,'devParamDevQuery','查询','G04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0402',NULL,'devParamDevRelease','下发','G04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0403',NULL,'devParamQuery','查询','G04','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0404',NULL,'devParamSave','保存','G04','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G06',NULL,'paramMonitor','参数下发监控','G','0');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0601',NULL,'paramMonitorQuery','查询','G06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0602',NULL,'paramMonitorDetail','保存','G06','1');
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('G0603',NULL,'paramMonitorTaskQuery','查询','G06','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G04','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0401','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0402','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0403','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0404','1');

INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G06','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0601','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0602','1');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('G0603','1');

INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON) VALUES ('F12', null, 'faultRate','故障率报表','F','0');
INSERT INTO SM_ROLE_PERMISSION(PERMISSION_ID,ROLE_ID) VALUES ('F12','1');
