ALTER TABLE ATMC_CASH_INIT ADD COLUMN DATES INT NOT NULL DEFAULT 0;
ALTER TABLE ATMC_SETTLEMENT ADD COLUMN DATES INT NOT NULL DEFAULT 0;
INSERT INTO SM_PERMISSION(PERMISSION_ID,PER_ACTION,CODE,DESCRIPTION,PARENT_ID,IS_BUTTON,ICON_CLS) VALUES ('A12', null, 'deviceView','单击模式','A','0','');
