alter table PARAM_PUBLISH add column PUBLISHER_TYPE int default 1;


CREATE TABLE PARAM_PUBLISH_APP_RESULT(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	APP_SYSTEM_ID BIGINT(20) NOT NULL,
	PARAM_PUBLISH_RESULT_ID BIGINT(20) NOT NULL,
	STATUS VARCHAR(15) DEFAULT NULL,
	REASON VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;